### ISSUE TITLE
Wireframing

### ISSUE THREAD

**Issue by ShubhamThakur025** [ShubhamThakur025/Krishi#1]
**Wireframing**
Add wireframing for the web and mobile view.

**Tasks:**

- [x] Create a low fid design for desktop view.
- [x] Create a low fid design for mobile view.
- [x] Create a high fid for desktop view [Front-Page].
- [x] Create a high fid for mobile view [Front-Page].

**Comment by ShubhamThakur025** [comment]
Create a low fid design for desktop view.
 
 In #15
