### ISSUE TITLE
Add Login logic [Backend]

### ISSUE THREAD

**Issue by ShubhamThakur025** [ShubhamThakur025/Krishi#12]
Add the logic for login in the backend.

**Tasks:**
- [x] Create a basic logic.
- [x] Add validation through middleware - Joi.
- [x] Update Routes
- [x] Update Controllers.
- [x] Issue token for authentication and authorization.

**Comment by ShubhamThakur025** [comment]
Resolved in #30
