### ISSUE TITLE
Dashboard for the farmer

### ISSUE THREAD

**Issue by ShubhamThakur025** [ShubhamThakur025/Krishi#13]
Create a Dashboard for the farmer.

**Tasks:**

- [ ] Add a dashboard for the farmer.
- [ ] Add a section on top - To find buyers.
- [ ] Add other relevant sections as per the wireframe.
