### ISSUE TITLE
Chat functionality

### ISSUE THREAD

**Issue by ShubhamThakur025** [ShubhamThakur025/Krishi#18]
**Chat functionality**

**Tasks:**

- [x] Add a chat functionality for the two ends to communicate with each other.
- [x] Integrate it with frontend
- [x] Respect the color scheme

**Comment by ShubhamThakur025** [comment]
Resolved in #30
