### ISSUE TITLE
Develop Express App

### ISSUE THREAD

**Issue by ShubhamThakur025** [ShubhamThakur025/Krishi#3]
**Develop Express App**

**Tasks:**
- [x]  Add the folder structure - config, controllers, models, routes
- [x] Add cors - middleware
- [x] Add Express.json() - middleware
- [x] Add server.js file
- [x] Add Nodemon
- [x] Add scripts - start and dev.
- [x] Other relevant code.

**Comment by ShubhamThakur025** [comment]
Resolved in #9.
