### ISSUE TITLE
Update the dashboard

### ISSUE THREAD

**Issue by ShubhamThakur025** [ShubhamThakur025/Krishi#34]
**Tasks:**

- [ ] Update the UI as per the design.
- [ ] Add links for knowledge Hub.
- [ ] Add link for confirming bids or downloading contracts.
